# Generated by Django 5.0 on 2023-12-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_verif_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verif_code',
            field=models.CharField(default='713844822317', max_length=15, verbose_name='Проверочный код'),
        ),
    ]
