# Generated by Django 5.0 on 2023-12-24 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата оплаты')),
                ('amount', models.PositiveIntegerField(verbose_name='Сумма оплаты')),
                ('method', models.CharField(choices=[('CASH', 'Наличные'), ('TRANSFER', 'Перевод на счет')], max_length=25, verbose_name='Способ оплаты')),
                ('course', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.SET_NULL, to='study.course', verbose_name='Оплаченный курс')),
                ('lesson', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.SET_NULL, to='study.lesson', verbose_name='Оплаченный урок')),
                ('owner', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Владелец платежа')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
    ]
